### PR TITLE
Make conf.py work on RTD

### PR DESCRIPTION
**Pull request by jankatins**
I've tried this in my own RTD account for this repo, but it would be nice if someone could setup RTD for the main repo:
- Import the repo in the account
- under advanced settings -> check "Install your project inside a virtualenv using setup.py install" & add a "docs/requirements.txt" as a doc requirement & make it python3.x

### CODE REVIEW

**Comment by jankatins** [comment]
http://jasc-ipython-extensions.readthedocs.org/en/latest/magics.html

**Comment by jankatins** [comment]
Thanks for granting me access to the repo. I will setup a RTD site for the project. Who else wants to access to the site? I can handle the site, but it would be nice if there is a backup...

**Comment by jankatins** [comment]
Ok, Seems that I don't have access to the repo, at least I can't setup the RTD hook (no access to the settings) and I can't merge PRs (aka this one :-))

**Comment by juhasch** [comment]
I can't give you access, but at least I can merge it.

**Comment by jankatins** [comment]
@juhasch Thanks

**Comment by jankatins** [comment]
Ok, please add your RTD names here,so that I can add you... http://ipython-extensions.readthedocs.org/en/latest/

**Comment by Carreau** [comment]
> Thanks for granting me access to the repo.

I should have given you Owner access to the **organisation** (I retried in case it did not work)  you might need to tweak yourself the permission on the repo.

I also gave Owner access to @juhasch because I was sure he already had it, which was not the case.

**Comment by jankatins** [comment]
@Carreau Thanks, I installed the webhook, so we now have automatic docs builds for each push to master :-)

**Comment by Carreau** [comment]
> @Carreau Thanks, I installed the webhook, so we now have automatic docs builds for each push to master :-)

Thanks !

**Pull request merged**
