### PR TITLE
Init repo

### PR DESCRIPTION
**Pull request by jankatins**
Add the initial files for the repo:
- License as in IPython (mostly s/IPython/IPython-extensions/)
- one extension + tests
- travis integration (needs activation)
- doc generation (-> RTD activation?)
- Contributing guide

Closes: #1

### CODE REVIEW

**Comment by juhasch** [comment]
Thanks, basically looks good. With a few things I would like to start a slower:
- `.travis.yml` -  let's first get the repo started before we look at travis
- `docs/source/links.txt` - what do we need this for
- `docs/source/whatsnew/...` - who will take care of whatsnew? Let's keep this repo slim
- `docs/sphinxext/github.py` ?

General structure:
- all extensions in `ipyext` or in something like `source` or `extensions` and then giving each extension it's own directory?
- do we place tests with the extensions. I usually have a common `tests` directory.

**Comment by jankatins** [comment]
slimmed down the docs: whatsnew is now a simple page. IMO that's probably ok for this package.

**Comment by jankatins** [comment]
I tried to separate the extensions (a few from minrks repo) into a few topic related folders, but right now I didn't find any suitable criteria. "debugging" is sometimes "coding" and "usability" is something which usually belongs to the notebook. So I ended up with adding all extensions in one directory. I think it is still ok, matplotlib has 50+ py files under matplotlib and I don't think we end up with that many extensions. If we do we can move files and add deprecation warnings in the old location.

I also like a common test dir, hence the current test subdir in ipyext. Or do you mean a test dir next to ipyext?

**Comment by jankatins** [comment]
I like the idea to turn on travis right on the start. I keeps me on track when I start adding features :-) I can remove that commit and add a new PR.

**Comment by juhasch** [comment]
I have no strong opinion on directory naming. Let's keep it this way, have all extensions in one directory and a `tests` directury for the tests.

For me this is fine to merge.

**Comment by damianavila** [comment]
> I have no strong opinion on directory naming. Let's keep it this way, have all extensions in one directory and a tests directury for the tests.

I agree...

> For me this is fine to merge.

Let's iterate quick on this and we can refine later...

**Comment by jankatins** [comment]
With or without travis commit?

**Comment by damianavila** [comment]
It is ok for me... unless @juhasch is very strong against that...

**Comment by juhasch** [comment]
If it is useful for you, sure.

**Comment by jankatins** [comment]
Thanks :-) Can someone with admin rights in this repo do the travis connect (and RTD, but that's no as important... :-))

**Comment by damianavila** [comment]
Already connected on Travis...

**Comment by jankatins** [comment]
@damianavila Thanks! Will post a PR with another extension from minrk to try it out...

**Pull request merged**
